stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: user-manager-mongo-front
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

containerization:
  stage: containerization
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${DOCKER_IMAGE} .
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}
    # Cleanup
    - docker image rm ${DOCKER_IMAGE}
